---
title: "Injuries in Office and Non-Office Workers"
format: html
---

# Conclusion

This report examined injuries among office and non-office workers and found that while office workers experience injuries at a higher overall frequency, non-office workers suffer injuries that are more severe on a per injury basis and lead to more days away or restricted at work. It is when we account for both the injury frequency and the injury severity that we can see that overall loss of productivity is the same. By comparing the number of days that are lost per 100,000 hours worked we find that the office workers and non office workers lose the same amount of days not able to work. Any company would want to reduce the number of days their employees could not work but the strategies employed could be representative to the type of work and value done by office and non-office employees. These differences may reflect how companies perceive the replaceability of employees. Office workers often possess specialized knowledge or Institutional knowledge that are difficult to replace quickly. As a result a greater emphasis is placed on preventing long term absences and ensuring that if there is an injury it is addressed before becoming severe. In contrast non-office workers participate in manual labor positions where replacement labor may be easier or less difficult to train. Meaning companies may be less incentivised to properly protect non-office workers, which could contribute to more severe injuries  observed in these occupations. 


Several limitations should be noted when interpreting the findings of this report. First, companies with fewer than 250 employees are not always required by law to report injuries unless they have received a written request from OSHA or the BLS which means that there are some workplace injuries that were not included in the dataset. Secondly the Injury Tracking Application does not track when an injury has been sustained on the job making it impossible for the employee to continue potentially underrepresenting the severity of injuries. Third the NAICS codes classify the work of the company rather than the specific responsibilities  of individual employees at the company limiting the reliability of comparing across industry types. Finally, workplace injuries may be underreported due to company culture or lack of awareness regarding regulatory requirements.


As for how to reduce general workplace injuries across both office and non-office environments companies should follow common sense safety measures. Maintaining clean and well organized workspaces can reduce slips, trips, and the spread of illness. Regular training of employees about relevant safety procedures and regulatory requirements to  ensure workers remain informed. Providing appropriate and effective personal protective equipment (PPE) for what employees need on the job will minimize exposure to workplace hazards.Additionally, ensuring  tools, machinery, and vehicles have maintenance done regularly can help prevent unforeseen malfunctions that lead to accidents. The implementation or continuation of these general guidelines can improve employee safety and improve company performance by reducing the number of days an employee is not able to perform their responsibilities.
